### ISSUE TITLE
ParseStatementResultAsync throws error when More property is 'empty' on SCORM Cloud LRS

### ISSUE THREAD

**Issue by nielsvand** [MindOnSite/FluentxApi#17]
SCORM Cloud returns a value of `""` on the `more` property, if the property is not set. This causes `LrsClient.ParseStatementResultAsync` to fail (it only handles a value of `null`).

I fixed this by changing line 331 from

`if (result["more"] != null )`

to

`if (result["more"] != null && !string.IsNullOrWhiteSpace(result["more"].Value<string>()))`

**Comment by Gimly** [comment]
Are you willing to create a pull request ? If so, I will gladly merge it and push a new version. Otherwise, I can also make the change myself.

**Comment by nielsvand** [comment]
I'm afraid I can't figure out how to create the PR (I use Sourcetree). Whatever I try, I receive an access denied.. so if you are willing to make the change?

**Comment by Gimly** [comment]
That's because you cannot publish code directly in this repository, you have to first create a fork, you can get more information here https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks.

I did the changes and published a 0.10.0 which should fix the issue.

But, it's relatively strange, it mans that they have an issue with their xAPI implementation, you should never have an empty property in a xAPI response, the property should not be present.

**Comment by nielsvand** [comment]
Thanks! Next time I will create the PR myself..

The xAPI specification states for the **more** property (section 2.5):

> Relative IRL that can be used to fetch more results, including the full path and optionally a query string but excluding scheme, host, and port. Empty string if there are no more results to fetch.

So the empty string is actually the correct behavior.

**Comment by Gimly** [comment]
OK, my bad then 😄, I was sure they had the "if empty then it shouldn't be present in the json" rule everywhere.

But thanks, it's great to see that library being used and improved !
